"use strict";

import { gsap } from "gsap";
import main from "../css/sass/main.scss";
import inline from "../css/sass/inline.scss";

import headerScrolling from "./scripts/headerScrolling";
import mobileMenu from "./scripts/mobileMenu";
import megaMenu from "./scripts/megaMenu";
import headerSearch from "./scripts/headerSearch";
import inputSelect from "./scripts/inputSelect";
import accordion from "./scripts/accordion";
import gsapAnimations from "./scripts/gsapAnimations";
import anchorScroll from "./scripts/anchorScroll";
import testimonials from "./scripts/slider/testimonials";
import heroSlider from "./scripts/slider/hero";
import tourListSlider from "./scripts/slider/tour-list";
import productSlider from "./scripts/slider/product-slider";
import categorySlider from "./scripts/slider/category-slider";
import featuredProducts from "./scripts/slider/featured-products";
import productGrid from "./scripts/slider/product-grid";
import benefitsSlider from "./scripts/slider/benefits-slider";
import contactCidades from "./scripts/contactCidades";
import blogFilter from "./scripts/blogFilter";
import blogHeroSlider from "./scripts/slider/blog-hero";
import contactForm from "./scripts/contactForm";
import singleProduct from "./scripts/single-product";
import categoryFilter from "./scripts/categoryFilter";
import cartSidebar from "./scripts/cartSidebar";
import checkoutLayout from "./scripts/checkoutLayout";
import cepAutofill from "./scripts/cepAutofill";
import shippingMethodToggle from "./scripts/shippingMethodToggle";
import deliveryDateReposition from "./scripts/deliveryDateReposition";

window.gsap = gsap;

headerScrolling();
mobileMenu();
megaMenu();
headerSearch();
inputSelect();
accordion();
gsapAnimations();
anchorScroll();
testimonials();
heroSlider();
tourListSlider();
productSlider();
categorySlider();
featuredProducts();
productGrid();
benefitsSlider();
contactCidades();
blogFilter();
blogHeroSlider();
contactForm();
singleProduct();
categoryFilter();
cartSidebar();
checkoutLayout();
cepAutofill();
shippingMethodToggle();
deliveryDateReposition();
